name: NPM build DEV

on:
    push:
        branches: ["master"]
    pull_request:
        branches: ["master"]

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - name: action-slack
              uses: 8398a7/action-slack@v3
              with:
                  status: custom
                  custom_payload: |
                      {
                        attachments: [{
                       text: ':arrow_forward: Start Build GBTem dev_test(${process.env.AS_COMMIT})',
                       color: '#0101DF'
                       }]
                      }
              env:
                  SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }} # required
              if: always() # Pick up events even if the job fails or is canceled.

 
            - name: action-slack
              uses: 8398a7/action-slack@v3
              with:
                  status: ${{ job.status }}
                  author_name: fGBTem dev_test # default: 8398a7@action-slack
                  fields: repo,message,commit,author,action,eventName,ref,workflow,job,took
              env:
                  SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }} # required
              if: always() # Pick up events even if the job fails or is canceled.
